version: '3'

services:
  survey:
    build: survey_server/
    depends_on:
      - 'database'
    ports: 
      - '8080:8080'

  results:
    build: results_server/
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    image: mongo:latest
